iname: "Security Gates Composite Action"
description: "Güvenlik tarama adımlarını içeren composite action"
inputs:
  example-input:
    description: "Örnek input"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Gitleaks Taramasını Çalıştır
      shell: bash
      run: |
        ./gitleaks detect --redact --exit-code 1

    - name: Semgrep Taramasını Çalıştır
      shell: bash
      run: |
        python3 -m pip install semgrep
        semgrep ci --config=auto --text

