name: security-gates

on:
  workflow_call:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  security-gates:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV


      - name: Run Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.22.1/gitleaks_8.22.1_linux_x64.tar.gz && tar -xzf gitleaks_8.22.1_linux_x64.tar.gz
          START=$(date +%s); ./gitleaks detect --source . --report-format sarif --report-path gitleaks.sarif --redact || true; END=$(date +%s)
          echo "GITLEAKS_DURATION=$((END - START))" >> $GITHUB_ENV
          
      - name: Commit Secret Scan Alert
        run: |
          gitleaks detect --log-opts="--max-count=1 $GITHUB_SHA" --report-path commit-gitleaks.sarif --redact || true;

      - name: Run Semgrep Scan
        run: |
          pip install semgrep
          START=$(date +%s); semgrep scan --config="p/default" --sarif --output=semgrep.sarif || true; END=$(date +%s)
          echo "SEMGREP_DURATION=$((END - START))" >> $GITHUB_ENV

      - name: Run Grype SBOM scan
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          START=$(date +%s); grype dir:. -o sarif > grype.sarif || true; END=$(date +%s)
          echo "GRYPE_DURATION=$((END - START))" >> $GITHUB_ENV


      - name: Upload Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always() && github.event.repository.private == false
        with:
          sarif_file: .
          checkout_path: ${{ github.workspace }}

      - name: Compute vulnerability counts
        id: vuln_count
        run: |
          S_TOTAL=$(jq '[.runs[].results[]?] | length' semgrep.sarif || echo 0)
          G_CRIT=$(jq '[.runs[].results[]? | select(.properties.severity == "Critical")] | length' grype.sarif || echo 0)

          
          if [ -f gitleaks.sarif ]; then
            LEAK_COUNT=$(jq '[.runs[].results[]?] | length' gitleaks.sarif || echo 0)
            
           
            echo "LEAKS_DETAILS<<EOF" >> "$GITHUB_ENV"
            jq -r '.runs[].results[]? | "\(.locations[0].physicalLocation.artifactLocation.uri):\(.locations[0].physicalLocation.region.startLine)"' gitleaks.sarif >> "$GITHUB_ENV"
            echo "EOF" >> "$GITHUB_ENV"
          else
            LEAK_COUNT=0
            echo "LEAKS_DETAILS=Bulgu yok." >> "$GITHUB_ENV"
          fi
  
          echo "LEAKS_COUNT=$LEAK_COUNT" >> "$GITHUB_ENV"
          echo "S_TOTAL=$S_TOTAL" >> "$GITHUB_ENV"
          echo "G_CRITICAL=$G_CRIT" >> "$GITHUB_ENV"
          
           if [ -f commit-gitleaks.sarif ]; then
            CURRENT_LEAK_COUNT=$(jq '[.runs[].results[]?] | length' commit-gitleaks.sarif || echo 0)  
            echo "CURRENT_LEAKS_DETAILS<<EOF" >> "$GITHUB_ENV"
            jq -r '.runs[].results[]? | "\(.locations[0].physicalLocation.artifactLocation.uri):\(.locations[0].physicalLocation.region.startLine)"' commit-gitleaks.sarif >> "$GITHUB_ENV"
            echo "EOF" >> "$GITHUB_ENV"
           else
            LEAK_COUNT=0          
            echo "CURRENT_LEAKS_DETAILS= Commit'te Bulgu yok." >> "$GITHUB_ENV"
           fi
      
      - name: Send to Elastic
        env:
          CA_CERT: ${{ secrets.APPSEC_CA }}    
        run: |
          TOTAL_DURATION=$(( $(date +%s) - START_TIME ))
          echo "$CA_CERT" > trendyolrootca.crt

          PAYLOAD=$(jq -n \
            --arg timestamp "$(date --utc +'%Y-%m-%dT%H:%M:%SZ')" \
            --arg repo "${{ github.repository }}" \
            --arg leaks "$LEAKS_COUNT" \
            --arg s_total "$S_TOTAL" \
            --arg g_crit "$G_CRITICAL" \
            --arg total_dur "$TOTAL_DURATION" \
            '{
              "@timestamp": $timestamp,
              "repository": $repo,
              "vulnerability_summary": {
                "gitleaks": ($leaks | tonumber),
                "semgrep_total": ($s_total | tonumber),
                "grype_critical": ($g_crit | tonumber)
              },
              "total_duration_sec": ($total_dur | tonumber)
            }')

          curl -X POST "${{ secrets.APPSEC_ELASTIC_URL }}" \
            -u "${{ secrets.APPSEC_ELASTIC_USER }}:${{ secrets.APPSEC_ELASTIC_PASS }}" \
            --cacert trendyolrootca.crt -H "Content-Type: application/json" -d "$PAYLOAD"

      - name: Slack Notification
        if: env.CURRENT_LEAKS_COUNT != '0'
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          MESSAGE=":rotating_light: *Son Commit'te Gitleaks Secret Bulguları Tespit Edildi! İnceleme Gerekli <!subteam^S094H6SEC06|appsec-oncall>*
          *Repo:* "https://github.com/${{ github.repository }}"
          Commit: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          Kullanıcı: "https://github.com/${{ github.actor }}"
          *Toplam Bulgu:* $CURRENT_LEAKS_COUNT

          *Bulguların Listesi:*
          \`\`\`
          $CURRENT_LEAKS_DETAILS
          \`\`\`"
          
          PAYLOAD=$(jq -n --arg msg "$MESSAGE" '{text: $msg}')
          
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
